name: 'Terraform Deploy via WIF'

on:
  push:
    branches: [ main ]

# CRITICAL: You must explicitly request these permissions for OIDC to work!
permissions:
  contents: 'read'
  id-token: 'write' # This allows GitHub to mint the OIDC token

jobs:
  # terraform-scan:
  #   name: 'Terraform Scan'
  #   runs-on: ubuntu-latest

  #   # Tell GitHub Actions that every 'run' step in this job 
  #   # should execute inside the './sample-project' folder
  #   defaults:
  #     run:
  #       working-directory: ./sample-project

  #   steps:
  #   - name: 'Checkout Repository'
  #     uses: actions/checkout@v4

  #   - name: Run Checkov IaC scan
  #     uses: bridgecrewio/checkov-action@master
  #     with:
  #       directory: /
  #       framework: terraform
  #       output_format: cli
  #       skip_check: >-
  #         CKV_GCP_42,
  #         CKV_GCP_49,
  #         CKV_GCP_125

  terraform-plan:
    name: 'Plan'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sample-project
    outputs:
      has_changes: ${{ steps.plan.outputs.has_changes }}
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER_NAME }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.14.4"
          terraform_wrapper: false

      - run: terraform init

      - name: 'Terraform Plan'
        id: plan
        continue-on-error: true
        env:
          TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
          TF_VAR_terraform_service_account: ${{ secrets.GCP_SA_EMAIL }}
        run: |
          # Temporarily disable 'exit on error' so the script doesn't crash when Terraform returns 2
          set +e 
          terraform plan -detailed-exitcode -out=tfplan
          EXIT_CODE=$?
          set -e # Re-enable 'exit on error' for the rest of the script

          if [ $EXIT_CODE -eq 2 ]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          elif [ $EXIT_CODE -eq 0 ]; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected."
          else
            echo "Terraform plan failed with exit code $EXIT_CODE"
            exit $EXIT_CODE
          fi

      - name: 'Upload Plan'
        if: steps.plan.outputs.has_changes == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ./sample-project/tfplan

  debug-logic:
    name: 'Debug Variables'
    needs: terraform-plan
    runs-on: ubuntu-latest
    steps:
      - name: 'Print Evaluated Outputs'
        run: |
          echo "=== DEBUG INFO ==="
          echo "has_changes: '${{ needs.terraform-plan.outputs.has_changes }}'"
          echo "=================="

  terraform-apply:
    name: 'Apply'
    needs: terraform-plan
    # Only run if there are actual changes
    if: needs.terraform-plan.outputs.has_changes == 'true'
    runs-on: ubuntu-latest
    # pauses the job and waits for the reviewer in the 'production' environment
    environment: production
    defaults:
      run:
        working-directory: ./sample-project
    steps:
      - uses: actions/checkout@v4
        with:
            submodules: 'recursive'
      - uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: ./sample-project

      - name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER_NAME }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.14.4"

      - run: terraform init

      - name: 'Terraform Apply'
        run: terraform apply -auto-approve tfplan