name: 'Terraform Deploy via WIF'

on:
  push:
    branches:
      - main

# CRITICAL: You must explicitly request these permissions for OIDC to work!
permissions:
  contents: 'read'
  id-token: 'write' # This allows GitHub to mint the OIDC token

jobs:
  # terraform-scan:
  #   name: 'Terraform Scan'
  #   runs-on: ubuntu-latest

  #   # Tell GitHub Actions that every 'run' step in this job 
  #   # should execute inside the './sample-project' folder
  #   defaults:
  #     run:
  #       working-directory: ./sample-project

  #   steps:
  #   - name: 'Checkout Repository'
  #     uses: actions/checkout@v4

  #   - name: Run Checkov IaC scan
  #     uses: bridgecrewio/checkov-action@master
  #     with:
  #       directory: /
  #       framework: terraform
  #       output_format: cli
  #       skip_check: >-
  #         CKV_GCP_42,
  #         CKV_GCP_49,
  #         CKV_GCP_125
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./sample-project
    outputs:
      is_risky: ${{ steps.check_risk.outputs.is_risky }}
    steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@v4
      with:
        submodules: 'recursive' # If your repo has submodules, this ensures they are also checked out

    - name: 'Authenticate to Google Cloud'
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/588269308956/locations/global/workloadIdentityPools/github-actions-pool-v2/providers/github-actions-provider'
        service_account: 'asukov-tf-rw@boxwood-bee-484209-r9.iam.gserviceaccount.com'
        export_environment_variables: true
    
    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.14.4" # Match your FAST version
    - name: 'Terraform Init'
      run: terraform init

    - name: 'Terraform Plan'
      id: plan
      run: terraform plan -out=tfplan
    
    # This step inspects the plan for any 'delete' or 'update' actions
    - name: 'Check for Deletions or Modifications'
      id: check_risk
      run: |
        terraform show -json tfplan > tfplan.json
        # Count resources with 'delete' or 'update' actions
        RISKY_CHANGES=$(jq '[.resource_changes[]?.change.actions[] | select(. == "delete" or . == "update")] | length' tfplan.json)

        echo "Risky changes count: $RISKY_CHANGES"

        if [ "$RISKY_CHANGES" -gt 0 ]; then
          echo "risky=true" >> $GITHUB_OUTPUT
        else
          echo "risky=false" >> $GITHUB_OUTPUT
        fi
    
    - name: 'Upload Plan Artifact'
      uses: actions/checkout@v4 # Re-using checkout logic for artifact paths
      with:
          path: tfplan
    - uses: actions/upload-artifact@v4
      with:
        name: tfplan
        path: ./sample-project/tfplan    

  terraform-apply:
    name: 'Terraform Apply'
    needs: terraform-plan
    runs-on: ubuntu-latest
    
    # This triggers the manual approval if risky is true
    environment: ${{ needs.terraform-plan.outputs.is_risky == 'true' && 'production' || 'none' }}
    defaults:
      run:
        working-directory: ./sample-project

    steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@v4
      with:
        submodules: 'recursive' # If your repo has submodules, this ensures they are also checked out
    - name: 'Download Plan Artifact'
      uses: actions/download-artifact@v4
      with:
        name: tfplan

    - name: 'Authenticate to Google Cloud'
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/588269308956/locations/global/workloadIdentityPools/github-actions-pool-v2/providers/github-actions-provider'
        service_account: 'asukov-tf-rw@boxwood-bee-484209-r9.iam.gserviceaccount.com'

    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.14.4" # Match your FAST version

    # 3. Run Terraform (It automatically uses the auth from Step 1)
    - name: 'Terraform Init'
      run: terraform init
    
    - name: 'Debug Directory Contents'
      run: |
        pwd
        ls -la

    # - name: 'Force Unlock State'
    #   run: terraform force-unlock -force 1776780558207852

    - name: 'Terraform Apply'
      run: terraform apply -auto-approve tfplan